### ISSUE TITLE
Device not implemented.

### ISSUE THREAD

**Issue by YaanLaxity** [marcsowen/homebridge-homematicip#100]
Hi there.
I am running Homebridge in a Docker container and am tinkering with the HM IP Plugin and get the Error:

[HomematicIP] Device not implemented: HmIP-ASIR - Alarmsirene via type ALARM_SIREN_INDOOR

The other device is HmIP-HAP - Access Point via type HOME_CONTROL_ACCESS_POINT which i already read about ignoring it. Same with the ASIR?

Love the plugin so far...

Greetings Yaan (willing to test, if necessary)

**Comment by marcsowen** [comment]
Hi. It's not really an error. The device is not implemented directly on HomeKit side, but it will still work as designed via the HomematicIP cloud. The siren doesn't have any useful device settings which could be controlled via HomeKit. But you can control the "Home Security System" via HomeKit which will in turn trigger the siren as configured in the HomematicIP app.

Same applies for the access point. The access point is indirectly supported (of course, otherwise you couldn't control anything). But the device itself doesn't have any useful settings which qualifies it as a real HomeKit device.

Thank you for your support. If you have any other device which is not supported right now, please let me know.

**Comment by YaanLaxity** [comment]
Hi. Thank you very much, i appreciate the explanation. I already made the installation on a real Raspberry and it is working pretty good!

If you need another idea for a new plugin - i have one! I am currently using it with CMDTRIGGER but i think there could be a nice plugin version. Not related to HMIP though...
