### ISSUE TITLE
Home Security System appears although not in place

### ISSUE THREAD

**Issue by MartinDdorf** [marcsowen/homebridge-homematicip#126]
Hi!
suddenly a new Device appeared: "Home Security System".
But i do not own or use any presence based devices in homematic IP - so this new device is useless but appears in all my rooms as suggestions.. i do not see any chance to hide it.. could you please take a look? 😀 Big THANKS!

<img width="117" alt="Ohne Titel 2021-05-30 21-55-02" src="https://user-images.githubusercontent.com/85079331/120118207-bbcb1780-c191-11eb-98f8-aa31000a4d22.png">

**Comment by marcsowen** [comment]
Hi @MartinDdorf ,

sorry for the late reply. Yes, you're right. The "Home Security System" is always shown since it's a basic function in the HomematicIP world. But it shouldn't appear in all rooms. You can assign the device to a room (e.g. standard room) and it should only appear there. You can also hide in from your favourites when changing the settings for this device.

I will look into it if I check for the presence of the "Security Zone" first. If you don't have a security zone the device definitely is useless. On the other hand, a simple door/window sensor is sufficient for the "Home Security System" to work as intended. (Alarm goes off in the app, when the window is opened. You don't need a siren for this.)

Marc

**Comment by MartinDdorf** [comment]
Hey! Thank you for your reply :-)
I did it exactly how you suggested, NOT as a favorite, in my "Bridges" room.
But if i watch to a camera in the Home app it shows me this Security device as the first device in the "Devices near to me" - the button in the left downer corner - although it is not belonging to the same room (i.e. Garage).





And there it is useless for me because i just do not use the security functionality.

**Comment by tomfrenzel** [comment]
@MartinDdorf I had the same issue as you. Got it working by executing the Following steps:

- Removing the official Plugin
- Cloning the repo and removing lines 29, 50, 172, 187, and 225 from homebridge-homematicip/src/HmIPPlatform.ts.
- From homebridge-homematicip/ executing the following commands: `npm install`,  `npm run build` and `npm link`
- Rebooting Homebride and adding the HmIP-HAP again

Although it's not the best solution and I'd rather prefer the Security Feature being configurable through the JSON config of this Plugin, this Solution should do the trick and it only takes about 5 minutes.

Lmk if it works for you

**Comment by Perilax-De** [comment]
First of all thank you for the plugin !

I also have the problem that the Home Security System is displayed although I don't use it.

It would be very convenient if I could select individual devices including the security system in the config, which are not displayed in Homebridge or Homekit.

That would be a very good function.

**Comment by reinisb** [comment]
@Perilax-De @marcsowen Same issue here - I would love if there was a legit way to not have Home Security System accessory. It is really confusing to have it show up in Home app when in fact I don't have any home security-related device.

**Comment by marcsowen** [comment]
You can now disable the "Home Security System". See Wiki for details:

https://github.com/marcsowen/homebridge-homematicip/wiki

**Comment by reinisb** [comment]
@marcsowen This worked perfectly, thanks a million!

**Comment by robertor85** [comment]
@marcsowen The code in the wiki doesn't work for my. It show me always a Syntax Error.
