### ISSUE TITLE
HmIP-FAL230-C6

### ISSUE THREAD

**Issue by decodrr** [marcsowen/homebridge-homematicip#130]
Let me first of all **thank you** guys for bringing the Homematic IP API set to Homebridge! This was the main reason for me to switch from "Home Assistant" to Homebridge (via HOOBS). It would also be great if you would get the "HOOBS Certified" label one day ;-) 

I have successfully connected a large number of Homematic IP devices to my HomeKit instance. The current temperature and humidity are correctly displayed from the HmIP-STHD devices in all rooms. 

However, I'm **not able to adjust the temperature for the rooms**. I'm using 4 (!) **HmIP-FAL230-C6** floor heating actors to manage heating on all four floors via HmIP-STHD. I was able to change room temperature via HomeKit with my Home Assistant implementation but it seems like this is not possible right now with "homebridge-homematicip".

**Could it be that you need to tell HomeKit that HmIP-STHD can be a thermostat instead of a sensor?** 

Are you working on this option? Is there anything I can do to make this work or test something for you?

Thank you!

**Comment by marcsowen** [comment]
Hi @decodrr ,

sorry for the late reply. Oh, I didn't know there is a HOOBS certification, but many people seem to use it, so it might be something to look into. :)

The HmIP-STHD used to be a simple room temperature and humidity sensor. Since version 0.5.0 I changed it to be a real thermostat in HomeKit. Can you first check if you have the latest version (0.5.0) of the homebridge-homematicip plugin installed?

Please let me know if this doesn't solve your problem.

**Comment by decodrr** [comment]
Moin @marcsowen ,

You have already identified the (first) issue! The version I'm running is 0.4.3.

I just checked the HOOBS.local plugin site and it says that the plugin in "up to date". 

If you go to the [HOOBS.org website for your plugin](https://plugins.hoobs.org/plugin/homebridge-homematicip), the last version is also 0.4.3.

Do you need to manually bring the version on the HOOBS plugin site to 0.5.0 or is there a way for you to automatically publish the latest version from GitHub/NPM to HOOBS?

Thank you!

**Comment by decodrr** [comment]
Moin @marcsowen ,

FYI, update to 0.5.1 now worked natively from HOOBS via the update button. 

Cheers!
