### ISSUE TITLE
How to handle HeatingCoolingState?

### ISSUE THREAD

**Issue by marcsowen** [marcsowen/homebridge-homematicip#18]
Sometimes it's apparent that HomeKit was developed in the US. In most homes in the US people have a single thermostat mounted on a wall at a central place in the house. Those thermostats usually are connected to a central combined heater/air-conditioner. From there air-tubes, which transport either cool or hot air, are connected to every single room of the house.

That's the reason why HomeKit supports four different HeatingCooling states:

- OFF (air-conditioner is off)
- HEAT (air-conditioner is heater mode, producing hot air)
- COOL (air-conditioner is in cooling mode, producing cool air)
- AUTO (air-conditioner decides for itself, whether to heat or cool)

If you are in HEAT mode, and the temperature rises above your target temperature, the air-conditioner simply turns off. Same applies for COOL mode. If the temperature falls below the target temperature, the air-conditioner also turns off. In AUTO mode, the air-conditioner either turns on the heater or the cooler except when the target temperature is reached and is stable.

My question is how to apply this to the HomematicIP (European) world?

Most people just have a radiator with a simple thermostat set to a target temperature. Looking at the HomeKit states, the closest mode would be HEAT mode with a set target temperature. Since I don't have a radiator around I'm not even sure if there is a dedicated OFF mode. Isn't the thermostat just set to a very low (minimal) temperature?

Some modern houses have floor heating systems. There it's not very different, but HomematicIP supports a cooling mode as well. The wall mounted thermostats with display even have a dedicated symbol for this:

[HmIP-WTH2 heating/cooling](https://sowennet.de/files/wth2_cooling.png)

You can read everything about the cooling mode in chapter 2.2.5:

[HowTo: Fußbodenheizung- und Heizungsanlagensteuerung mit Homematic IP](https://www.homematic-ip.com/downloads/download/handbuecher/Installationsbeispiel_HmIP-Fussbodenheizung.pdf
)

Anyway, this cooling mode is not very common and the question remains whether those prominent HomeKit modes should be used for a very seldom used function.

So I need a vote from you, how to implement it:

- Use dedicated cooling mode as defined by HomematicIP
- Leave it on HEAT for most people with a radiator (with optional OFF mode if supported)
- Switch between HEAT and COOL depending on the temperature difference between current and target temperature.
- Map HEAT/AUTO to HomematicIP MANU/AUTO (ECO? PARTY?) mode.
- Make it an configurable option

Thanks!

**Comment by MaxiKingXXL** [comment]
Would it be possible to make it dependent on the device?  HmIP-eTRV-B and  HmIP-eTRV-2 support HEAT only be design because of this I think it would be good to show them in Homekit as Heating device.

The settings like AUTOMATIC, MANUAL, PARTY or BOOST are group settings.

Usually the device will follow the Homematic config. Because of this it might be the best to show them by default as AUTO in Homekit.

**Comment by lurid-bogey** [comment]
My two cents: just set it to AUTO and leave it there.

**Comment by lurid-bogey** [comment]
I was thinking about this a lot and came up with the following.

First question: Is there a dedicated OFF mode. The answer is yes and no. You cannot turn the thermostat off from the outside, just set it to a very low temperature. But the device internally can decide for itself if it is ON or OFF. The criterion here ist the valve position. If the valve is set to 0% (fully closed) then the heating is OFF, otherwise it’s ON.

The second question is what do we do with the HEAT, COOL and AUTO modes. I believe we should consider the wording in the Home app. 

- If a device is set to HEAT, then the Home app says “Heating to xx°C”. 
- If a device is set to COOL, then the Home app says “Cooling to xx°C”. 
- If a device is set to AUTO, then the Home app says “Set to xx°C”. 

Here, I believe, only the wording “Set to ...” makes sense in the context of an European thermostat. The other choices (Heating to..., Cooling to...) I find not suitable.

That’s why I would like to suggest the following algorithm:
**1. If the valve of the thermostat is set to 0%, then display it as OFF.
2. Else, display it as AUTO.**

Concerning some of Marc’s ideas:
- Map HEAT/AUTO to HomematicIP MANU/AUTO (ECO? PARTY?) mode. – Please don’t do it. I believe this will be totally confusing for most of the users. I could never explain this to my grandmother and she would never understand it.
- Switch between HEAT and COOL depending on the temperature difference – this might work, but I feel it’s too much effort for too little gain. Just setting it to AUTO would be much simpler.

One more thing. The setting OFF/AUTO should be “read only”. Meaning, only the device itself should be able to change it, but not the user. If the user tries to set it to an unsupported mode, e.g. HEAT or COOL, then the setting should automatically jump back to AUTO or OFF.

So... That was a long read...
Once again my suggestion:
1. If the valve of the thermostat is set to 0%, then display it as OFF.
2. Else, display it as AUTO.

**Comment by mrtzlbm** [comment]
I would love to be able to configure this myself in a mapping table of sorts.
Alternatively I'd choose option two:
> Leave it on HEAT for most people with a radiator (with optional OFF mode if supported)

**Comment by marcsowen** [comment]
I need to clarify that there are actually two different modes:

- TargetHeatingCoolingState (OFF, HEAT, COOL, AUTO)
- CurrentHeatingCoolingState (OFF, HEAT, COOL)

The target heating cooling state is what you can set in the App, while the current heating cooling state is what is displayed. For the heater/cooler the target state is what you want the heater to do and the current state is what the heater/cooler is actually doing. The best way to show this is in the Eve-App:

![IMG_F337A8683030-1](https://user-images.githubusercontent.com/4557484/107330204-88189480-6ab1-11eb-8202-bc30b766cc74.jpeg)

The important thing here ist that the current state is actually missing the AUTO state. This makes sense since you *want* the heater to do everything e.g. in AUTO mode but the heater actually *is* in either HEAT, COOL or OFF state.

So for now, the current state usually is in HEAT mode. But I do support the dedicated COOL state supplied by HomematicIP, if someone actually uses the cold water floor heater function. Since I haven't figured out a way to get an actual OFF state from HomematicIP, the current state will never be OFF for now.

The target state is currently ignored. So you cannot use the setting to change anything in HomematicIP. If HomeKit wants to know the target state, the plugin will respond with AUTO for now. In the Apps this means the switch will be set to AUTO if you don't change it or do a pull-to-refresh in the Eve App.

I will consider making the target state a configurable option in the plugin, maybe with a mapping option as suggested by @mrtzlbm . So you could something like this:

- OFF -> ECO
- HEAT -> MANU in HomematicIP
- COOL -> BOOST
- AUTO -> Profile-Mode/Auto in HomematicIP

Or:

- OFF -> MANU
- HEAT -> Party-Mode
- COOL -> Profile-Mode 2
- AUTO -> Profile-Mode 1

Currently it is more like this:

- OFF -> unassigned
- HEAT -> unassigned
- COOL -> unassigned
- AUTO -> unassigned
