### ISSUE TITLE
HmIP-SRH Fenstergriffsensor only showing one state

### ISSUE THREAD

**Issue by smarthome43372** [marcsowen/homebridge-homematicip#42]
The HMIP-SRH is showing two states in the HMIP app (offen/gekippt, see little window symbol which is indicating that) but only one state "geöffnet" in HomeKit. 
Would be really great to adjust that. Many thanks

![image](https://user-images.githubusercontent.com/62788072/107846216-4b66d900-6de2-11eb-8a30-2f79b1f45992.png)

![image](https://user-images.githubusercontent.com/62788072/107846221-51f55080-6de2-11eb-8646-ae62a51434a5.png)

![image](https://user-images.githubusercontent.com/62788072/107846222-5a4d8b80-6de2-11eb-9b00-881bd88b5214.png)

**Comment by marcsowen** [comment]
I could implement a second "Door"/"Window"-service which has a currentPosition:

- position 0%: closed
- position 50%: tilted
- position 100%: open

I'll have a look at it.

**Comment by smarthome43372** [comment]
Sounds good. Thanks

**Comment by marcsowen** [comment]
Try version >= 0.3.0. The contact sensor now also has a window service with a current position of either 0% (closed), 50% (tilted) or 100% (open).

**Comment by thecem** [comment]
Could somebody post the Home tile showing close, tilted and open window?
Thanks a lot!

**Comment by smarthome43372** [comment]
Thanks for implementing. So far it's working. 
In detail view the status is shown as slider which can be adjusted manually which is a little bit confusing is an status indicator which shouldn't be adjustable. 
In tile view you can the partially open state as 50%
On top the status is shown twice - don't know why?

![image](https://user-images.githubusercontent.com/62788072/109421798-1e691780-79d9-11eb-8917-0caa7e09200e.png)

![image](https://user-images.githubusercontent.com/62788072/109421805-288b1600-79d9-11eb-8cec-3fe5ad44b9b8.png)

![image](https://user-images.githubusercontent.com/62788072/109421813-317be780-79d9-11eb-9f4d-9cbdbd4113e7.png)

![image](https://user-images.githubusercontent.com/62788072/109421843-507a7980-79d9-11eb-8416-ff2c0b1c35e6.jpeg)

![image](https://user-images.githubusercontent.com/62788072/109421849-583a1e00-79d9-11eb-8015-5ff83640186d.png)

![image](https://user-images.githubusercontent.com/62788072/109421864-69832a80-79d9-11eb-9bb7-28f293aff2b9.jpeg)

**Comment by marcsowen** [comment]
> In detail view the status is shown as slider which can be adjusted manually which is a little bit confusing is an status indicator which shouldn't be adjustable.

Yes. The plugin is limited to what Apple supports as accessory services. The "window service" is normally used for motor controlled windows (like a roof window), that's why you can manually change the position. You will see that the target position is ignored when looking at the logs. There is not dedicated "status" device which shows more than open/closed.

> On top the status is shown twice - don't know why?

Yes. See issue #60 . I have implemented to services for the window. One contact sensor (with contact / no contact) and the window service for motor controlled windows. The latter device can show the different positions of 0, 50 or 100%. We can either remove one of the devices or make it an configurable option (per device).

**Comment by marcsowen** [comment]
Try version >= 0.3.1. This will remove the additional contact sensor from the rotary handle sensor. Now the status should only be shown once.
