### ISSUE TITLE
Disconnected / Conncted messgages in log

### ISSUE THREAD

**Issue by MasterofKungfu9999** [marcsowen/homebridge-homematicip#66]
I get this log-messages:

6.3.2021, 21:10:47 [HomematicIP] HmIP websocket connected.6.3.2021, 21:10:57 [HomematicIP] HmIP websocket disconnected.
6.3.2021, 21:11:07 [HomematicIP] HmIP websocket connected.6.3.2021, 21:11:17 [HomematicIP] HmIP websocket disconnected.
6.3.2021, 21:11:27 [HomematicIP] HmIP websocket connected.6.3.2021, 21:11:37 [HomematicIP] HmIP websocket disconnected.
6.3.2021, 21:11:47 [HomematicIP] HmIP websocket connected.6.3.2021, 21:11:57 [HomematicIP] HmIP websocket disconnected.
6.3.2021, 21:12:08 [HomematicIP] HmIP websocket connected.6.3.2021, 21:12:18 [HomematicIP] HmIP websocket disconnected.

Is this normal

**Comment by MasterofKungfu9999** [comment]
i thin i got it. There was a parralel connection to iobroker

**Comment by marcsowen** [comment]
Yes, the web socket only allows one connection per auth token. Be sure to create a new auth token for homebridge-homematicip exclusively.

**Comment by modi80** [comment]
Hey, because I always deinstalled the Homebridge-Intesisweb Plugin (and restarted hoobs) after getting the error messages I did not notice, that the error also disappears after a complete Hoobs restart with the two plugins installed and configured. Obviously the automatic service restart after installing or configuring a new plugin is not enough to make it work correctly. But now it's ok- without the error messages!

**Comment by marcsowen** [comment]
@modi80 Good to hear. Still strange though.
