### ISSUE TITLE
HmIP-WTH-2 looks the same as a radiator thermostat 

### ISSUE THREAD

**Issue by Raeubervater** [marcsowen/homebridge-homematicip#82]
![3D775A85-6C77-4FBA-8E45-D12334971EE4](https://user-images.githubusercontent.com/68013111/112225093-8b647b80-8c2c-11eb-8bed-ca754b155e23.jpeg)

It would be great, if the WTH2 will be handled like the HmIP-STHD:
![63FF47CD-AF28-4C3E-A0AA-D3D55907B585](https://user-images.githubusercontent.com/68013111/112225657-67ee0080-8c2d-11eb-855d-75028c3b709f.jpeg)

**Comment by marcsowen** [comment]
Hi @Raeubervater . I always try to find the best match between a HomematicIP device and a HomeKit accessory. For the WTH-2 for me the best match was a HomeKit thermostat since it measures temperature and humidity and you can set the desired temperature. Since the HmIP-STHD is a temperature and humidity sensor, the best match in HomeKit world is an accessory with a temperature and a humidity service.

I don't have an influence on how the services are displayed in the Home app. If you open the Eve app, the services might be displayed differently. Also in the next iOS version the display could be changing again.

Right now I wouldn't want to change the accessory type, since for the WTH-2 I would loose the ability to set a temperature and for the HmIP-STHD it wouldn't make any sense to change it to a thermostat since you cannot set the temperature of this device directly.
